### ISSUE TITLE
不支持 CoreProtect v21.3(1.20.1)

### ISSUE THREAD

**Issue by LittleChest** [ApliNi/useTranslatedNames#1]
![image](https://github.com/ApliNi/useTranslatedNames/assets/81231195/5c5a4d0d-6cdc-4499-a57e-07ca5d5a72c7)
![image](https://github.com/ApliNi/useTranslatedNames/assets/81231195/56bb79b7-bdb7-4ec3-b330-eac88e06f1bf)
![image](https://github.com/ApliNi/useTranslatedNames/assets/81231195/4fcae5b8-3868-4264-b664-7e8f2f429d29)

**Comment by ApliNi** [comment]
修改配置 `replace-regex: '\{"color":"#31b0e8","text":"([a-z0-9_]+)§f[。|\.]"\}'`
