### ISSUE TITLE
求个1.20.2 的翻译配置

### ISSUE THREAD

**Issue by 347180440** [ApliNi/useTranslatedNames#3]
![image](https://github.com/ApliNi/useTranslatedNames/assets/107541071/ec45d056-b2dd-4012-b22f-358ba5b7ffc8)
![ZL%7(KTDXB(Y0CQLK8{7FCT_tmb](https://github.com/ApliNi/useTranslatedNames/assets/107541071/fb33c00a-1a50-4d1b-a13b-4f05a526d832)
list:
    # 检查消息长度是否小于此值
  - inspect-length: 320
    # 检查消息是否以此字符串开头
    inspect-prefix: '{"extra":[{"hov'
    # 替换, 使用正则表达式匹配
    replace-regex: '\{"color":"#31b0e8","text":"([a-z0-9_]+)§f[。|\.]"\}' # (中文) '\{"color":"#31b0e8","text":"([a-z0-9_]+)§f\。"\}'
    # 替换为
    replace-to: '{"color":"#31b0e8","hoverEvent":{"action":"show_text","contents":{"extra":[{"translate":"__TranslatedName__"},{"text":" §o§7点击复制§r"},{"text":"\n§8minecraft:__ItemName__"}],"text":""}},"clickEvent":{"action":"copy_to_clipboard","value":"__ItemName__"},"extra":[{"translate":"__TranslatedName__"},{"text":" §8__ItemName__"}],"text":""}'
    #   __ItemName__        = 正则匹配到的实体/物品/方块名
    #   __ItemType_show__   = 提供给 JSON hoverEvent 使用的物品类型 show_entity, show_item(block)
    #   __TranslatedName__  = 转换后用于翻译的名称 "entity.minecraft.allay"
    # {"translate":"__TranslatedName__"}

**Comment by ApliNi** [comment]
更新到最新版本, 并让插件自动生成配置即可
