### ISSUE TITLE
兼容folia

### ISSUE THREAD

**Issue by xiaoluofa** [ApliNi/useTranslatedNames#4]

**Comment by ApliNi** [comment]
你知道哪里能找到 Folia 最新的构建 (jar 文件) 吗? 

适配 Folia 应该不难, 但是我还没法编译 Folia.

**Comment by xiaoluofa** [comment]
> 你知道哪里能找到 Folia 最新的构建 (jar 文件) 吗?
> 
> 适配 Folia 应该不难, 但是我还没法编译 Folia.

https://github.com/sekaom/folia_build_action
不好意思没看到，QAQ

**Comment by xiaoluofa** [comment]
> 你知道哪里能找到 Folia 最新的构建 (jar 文件) 吗?
> 
> 适配 Folia 应该不难, 但是我还没法编译 Folia.

你插件我测试过，可以强制在folia上跑，但是我更新到1.20.4，就报错了。不过可能是老版本原因，你更新的我没测试

**Comment by xiaoluofa** [comment]
plugin加入folia-supported: true

**Comment by ApliNi** [comment]
原来是这样, 那新版本应该也没问题, 更新时注意要删除或更新配置文件

**Comment by xiaoluofa** [comment]
> 原来是这样, 那新版本应该也没问题, 更新时注意要删除或更新配置文件

经过测试，支持了，可以考虑出一个正式支持folia的版本

**Comment by ApliNi** [comment]
确实可以直接使用, 我测试了一些功能, 但不完整. 新版本在这里发布, 除了支持 Folia 没有任何改动
https://modrinth.com/plugin/usetranslatednames

感谢你的帮助
