### ISSUE TITLE
没有效果

### ISSUE THREAD

**Issue by cgw2023** [ApliNi/useTranslatedNames#9]
CoreProtect-22.4
ProtocolLib#726
folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf-25ee657
lunar 1.20.4
预设设定，安装后支援额外显示灰色字
![image](https://github.com/user-attachments/assets/cc57ae56-ed8b-4349-92cb-41e21e6d1b75)

**Comment by ApliNi** [comment]
你的客户端使用的是英文语言吗? 可以测试一下中文的原版客户端
